# Generated by Django 4.1.5 on 2023-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default='2018'),
            preserve_default=False,
        ),
    ]
